apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

resources:
  - secret.yaml
  - ../../base

components:
  - ../../variants

patchesStrategicMerge:
  - replicas.yaml
  - resources.yaml
