---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-demo
spec:
  template:
    spec:
      containers:
        - name: enqi/gin-demo
          resources:
            limits:
              cpu: 30m
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
