apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local
namePrefix: local-

resources:
  - secret.yaml
  - ../../base

components:
  - ../../variants

patchesStrategicMerge:
  - replicas.yaml
