apiVersion: v1
kind: Service
metadata:
  name: gin-demo
  labels:
    app: gin-demo
    version: v1
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: gin-demo
    version: v1
  type: NodePort
